### ISSUE TITLE
Injection fails with two constructors present (one @Autowired)

### ISSUE THREAD

**Issue by benze** [jmockit/jmockit1#222] opened 2015-10-23 15:42 UTC
I'm not sure if this is a bug, or by design.  I have 2 constructors defined for a class (one autowired and one not).

```
public class Counter {
    private Data data = new Data();
    
    @Autowired
    public Counter(Data data){
        this.data = data;
    }

    public Counter(){}
   
    public void printData(){
        System.out.println(data.toString());
    }
}
```

However, unless I defined a `@Injectable` in my test class, I get the following error:
```
java.lang.IllegalArgumentException: No constructor in tested class that can be satisfied by available injectables
  public test.Counter(test.Data)
    disregarded because no injectable was found for parameter "data"
```

Should JMockit not detect the ability to construct the class using the second empty constructor?  I'm using JMockit 1.19.

I would have expected the following test class to work:
```
@RunWith(JMockit.class)
public class CounterTest {
    @Tested(fullyInitialized=true) Counter counter;

    @Test
    public void testPrint(){
        counter.printData();
    }
}
```

Thanks,

Eric

**Comment by rliesenfeld** [comment] 2015-10-23 15:55
Constructor injection is not supported when using `fullyInitialized = true`, so you could say it's "by design".

**Comment by benze** [comment] 2015-10-23 15:56
I know/realize that constructor injection is not supported. But there is a second constructor available.  Why is the second constructor not used in that case?

**Comment by rliesenfeld** [comment] 2015-10-23 16:08
It's as described in the [API documentation](http://jmockit.org/api1x/mockit/Tested.html):

"For constructor injection, all constructor parameters (if any) must be satisfied with the values of available injectables. If the tested class has a constructor annotated with the standard CDI annotation "@Inject", then it is the one to be used; otherwise, if there are multiple satisfiable constructors then the one with the most parameters and the widest accessibility (ie, first public, then protected, then package-private, and finally private) is chosen."

Although constructor injection is not supported for `fullyInitialized`, a constructor still needs to be chosen and invoked whenever `@Tested` is used.

**Comment by rliesenfeld** [comment] 2015-10-23 16:18
Note that in a case like this, the test class can simply instantiate the SUT directly, without using `@Tested`:

    final Counter tested = new Counter();

**Comment by benze** [comment] 2015-10-23 18:49
Ok - but even if I mark the second constructor (no args) as `@Autowire` (just to be complacent for your framework), JMockit is still unable to find it.  I do not believe that the following is disallowed in CDI:
```
public class Counter {
    @Autowired
    private Data data = new Data();

    @Autowired
    public Counter(Data data){
        this.data = data;
    }

    @Autowired
    public Counter(){}

    public void printData(){
        System.out.println(data.toString());
    }
}
```


I realize that I can instantiate the SUT directly, but I'm trying to maintain constructor injection for my objects while still making them compliant for JMockit to use them (since it doesn't support constructor injection).

**Comment by rliesenfeld** [comment] 2015-10-23 19:06
Actually, only *one* constructor can be annotated with @Autowired, that's what the [API docs](http://docs.spring.io/autorepo/docs/spring-framework/3.0.x/api/org/springframework/beans/factory/annotation/Autowired.html) say. The same applies to CDI: at most one constructor using @Inject is allowed. So that's why JMockit only allows at most one such constructor, for compliance with the DI APIs.

Note that field injection will be better in this case (and every other case, as far as I can tell):

    public class Counter {
        @Inject private Data data;

        public Counter(Data data) { this.data = data; }
        public Counter() { data = new Data(); }
        ....
    }

**Comment by benze** [comment] 2015-10-23 19:09
Fair enough.  I missed that in the docs.  Thanks for pointing it out.

I'm still not convinced about the preference of field injection though.  Do you know of any recent documentation/blogs/etc that support the preference of field injection over constructor/setting injection?  I'm having trouble convincing others on the dev team, especially considering that I'm not particularly convinced myself.

Thanks!

Eric

**Comment by rliesenfeld** [comment] 2015-10-23 19:30
I will write an answer to the [SO question](http://programmers.stackexchange.com/questions/300706/dependency-injection-field-injection-vs-constructor-injection).

Beyond that, I noticed two small details in this case:
1) The original version of `Counter` has a bug: when `new Counter(data)` is used, there will be a second instance of `Data` (the one in the field initializer) that gets immediately lost, as the field is reassigned by the constructor. Perhaps using field injection would have avoided this bug.
2) One of the main advantages claimed for constructor injection is that it allows fields to be made `final`, which is generally a good idea. But in this case the field was *not* made `final`, so the potential advantage was lost. Personally, I make instance fields `final` whenever I can (which is most of the time), but I find it perfectly fine for *annotated* fields that are only meant to be assigned by a DI container to not be final; `final` is mostly useful to *document usage/design*, IMO, and use of @Inject/@Autowired on the field achieves the same goal.

**Comment by benze** [comment] 2015-10-23 19:44
Agreed; my test case is probably not the best example.  I was primarily trying to determine if/how I could make this work with multiple constructors.  But I had not realized that I was only allowed to have 1 injectable constructor (as defined in CDI and Spring).  Given that parameter, it is clear that my example (no matter how it is defined) will not be valid.

As for Constructor vs Field injection, I know you feel strongly about field injection being the way to go.  Which is why I would love to find additional documentation/opinions about this methodology to help convince myself as well as others around me to move in that direction.  Although I understand all your arguments for field injection, I find that the greatest drawback/shortcoming of it is that the class does not provide any indication of its requirements via its API.  If I am consuming someone else's library/class, I have no idea of its requirements unless someone has clearly written some javadocs explaining its dependency requirements.  Furthermore, given that private variables are not exposed in javadocs, without decompiling the .class files, I cannot know what objects types (and/or their bean names) I need to ensure are in my context such that my DI container is capable of injecting them.  A public injectable constructor clearly defines/provides this information.

I used to be very pro-field injection in the past, mostly b/c I didn't like boilerplate code, and I found that constructor injection to be difficult to use/maintain.  But after using it for a while, I can say that, while more verbose and more "clutter", I find it to be more intuitive and cleaner than field injection.

**Comment by rliesenfeld** [comment] 2015-10-23 20:09
I see now that the root for our different viewpoints is, simply, that we are thinking of entirely different use cases.

In my case, when I think of DI I am only considering the typical usage in business applications, where the classes that make use of DI annotations (@Inject, @Autowired) are all part of the codebase that is under development/maintenance. In this case, 3rd party libraries do not use DI themselves. So, there is no difficulty to find the annotated fields. I actually work with such codebases on a daily basis.

In your case, it seems that DI is used *across* the boundaries of multiple codebases, with 3rd party libraries or modules from other teams also making use of DI annotations. So, in this case the presence of DI annotations in public constructors or setter methods of external dependencies could, arguably, be useful. Admitedly, I have not seen this in a real-world project yet. Once I do see such a case, I might change my mind, at least for the use of constructor DI on reusable components (for internal, non-reusable components, I doubt I would ever lose favor for field injection).

**Comment by benze** [comment] 2015-10-23 20:22
Coming originally from a background where I worked on a central codebase, in which it was all open and modified together, I understand your point of view.  But I have since been working in larger enterprises that structure teams and applications differently.  Here, different teams are responsible for libraries/modules/etc and basically where I end up consuming a jar file.  Architects are responsible for defining the interfaces and the functionality that an interface is supposed to support.  So when a team tells me that their module is ready to use, all I should need is to look at the API that they have supplied me and I'm ready to go.

Although I do typically have access to the sources, I don't particularly want to go fishing through their code to figure out what fields are annotated, what they mean, etc.  It is much easier when it is provided clearly through their API (beit constructor or setter injection).

Spring originally started off its DI using only constructor & setter injections, but that was also due to it launching prior to the advent of annotations.  The fact that they have maintained support for the 3 different types (as well as Guice and CDI) clearly tells me that there is a need for them.

On a personal side, I would love to see support in JMockit for fully initialized constructor injection.  Right now, I think the lack of full constructor injection support is a major drawback - at least for use in our projects.

**Comment by rliesenfeld** [comment] 2015-10-23 20:30
Ok, I am starting to see the value in adding support for constructor injection when using `@Tested(fullyInitialized = true)`, even if I won't use it in my projects. I could even add it in the next couple days.

That said, do you think you could give a realistic example, where a component provided by another team is used, and that component uses DI annotations? I am trying to better understand the issue with "fishing through their code to figure out ..."; not saying there isn't, just it's not clear to me yet.

**Comment by benze** [comment] 2015-10-24 01:25
I am living through just such a situation at the moment.  Right now, I am developing a plugin to automatically create bugs/defects in our bug-tracking software (Rational Team Concert), using the RTC API.

In our organization, we have other needs to integrate with RTC so we have written our own REST wrapper for the RTC API (RTC natively provides a REST API but it is complicated to use and doesn't expose all the services we need).  It has been developed using SpringMVC (via Spring Boot) and the RTC API.

For my plugin, however, a decision was made to use our internal wrapper natively; not to use the REST interface.  So I'm importing our REST API as a dependency jar and directly instantiating/calling the services (bypassing the Controller layer altogether).

Given that our REST app is written using DI, and constructor injection, it is very easy for me to simply look at the the Services constructors and determine what parameters I need to ensure are in my context to work properly.

Additionally, I have the added advantage of either choosing to include the API lib in my context scanning (for auto DI injection), or to exclude the lib from the scanning and manually instantiate the beans using @Bean definitions.

I have no need to look at the sources of their code, or decompile anything.  All I need is the Impl constructor parameters.


If there is any way you could include constructor injection in 1.20, that would be amazing.

Thanks,

Eric

**Comment by rliesenfeld** [comment] 2015-10-24 14:10
Opened issue #224 to add the missing constructor DI support.

**Closed by rliesenfeld** 2015-10-24 14:10 UTC
Labels: question
